version: '1.0'
services:
  appoffer:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 4005
    ports:
      - 4005:4005
    env_file:
      - ./.env
    depends_on:
      - dboffer
  dboffer:
    image: postgres:13-alpine
    env_file:
      - ./.env.db