version: '3'
services:
  appoffer:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./.env
    depends_on:
      - dboffer
  dboffer:
    image: postgres:15.2-alpine
    env_file:
      - ./.env.db